[[ZstdSeekable]]
arch = "aarch64"
git-tree-sha1 = "787bf8564aadedab6038d84e8442ce4063e7d147"
os = "macos"

    [[ZstdSeekable.download]]
    sha256 = "d84f77e2cd81529a718cde03ee4a40d78f5f90c97e1c3aa9a6bd4c66a7a64832"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.aarch64-apple-darwin.tar.gz"
[[ZstdSeekable]]
arch = "aarch64"
git-tree-sha1 = "3b07e0857402cabc70597aa484736763f49b8bc3"
libc = "glibc"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "0c433aee55b5cafbc14826d75839c9742b6589efec1743674baeff84cc9bce93"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.aarch64-linux-gnu.tar.gz"
[[ZstdSeekable]]
arch = "aarch64"
git-tree-sha1 = "1e071281fb2dd86023635ea062cebe8acf105cb8"
libc = "musl"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "a70ad0eb9f455d96fc6010770ed12785410cdc924ef2b755b5957532b8c73b26"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.aarch64-linux-musl.tar.gz"
[[ZstdSeekable]]
arch = "aarch64"
git-tree-sha1 = "669542dc7eaa35b15db85761afb4c8cf15a730bf"
os = "freebsd"

    [[ZstdSeekable.download]]
    sha256 = "64de6d988c8d5aebf8f2bf871266b767a4c502d5cd362e99ebd9d0994e5a583d"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.aarch64-unknown-freebsd.tar.gz"
[[ZstdSeekable]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "106b0a12864e3e28aab7255ae689d1697f622e96"
libc = "glibc"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "d9d4393c4d9f0736de35f2aa4bd9318a09751d5cf0d768312a0ec2dbc6fb3899"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.armv6l-linux-gnueabihf.tar.gz"
[[ZstdSeekable]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c749236254c5493f0611383c96e7ec5bff255eb"
libc = "musl"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "a55ef3a40d4c09e8603034a55849db1ec154d96663e96940839d8894a106516c"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.armv6l-linux-musleabihf.tar.gz"
[[ZstdSeekable]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8768b509f8f63b4dd47a32216411e0675d3bb556"
libc = "glibc"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "8f657aa429aba5aaa365d790ce73877b80f384631072f096a14df63f5775f8df"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.armv7l-linux-gnueabihf.tar.gz"
[[ZstdSeekable]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3d1439e3850bf31743d6bc9f1178d9fd80c32968"
libc = "musl"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "b13aeaac2048390d19484ebc9e3f9b5ff142124df61c8a44131932e1492d7e4f"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.armv7l-linux-musleabihf.tar.gz"
[[ZstdSeekable]]
arch = "i686"
git-tree-sha1 = "52b1801785915bda2c9c088e767024f3b9f28b22"
libc = "glibc"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "b3028db49cf0744de8daecc525397a6119d94cd8f12889d79ff8fa7d17b5fe7c"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.i686-linux-gnu.tar.gz"
[[ZstdSeekable]]
arch = "i686"
git-tree-sha1 = "ecc21a521bde5facf647553da6859e090606e8e8"
libc = "musl"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "53053c7d3c63df392c10af52f5d0094f6936f57ef7a0cc4516ba8c3f72c94e41"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.i686-linux-musl.tar.gz"
[[ZstdSeekable]]
arch = "i686"
git-tree-sha1 = "d121aabad5bbb8e4082f255c0757ab8bbff4a65a"
os = "windows"

    [[ZstdSeekable.download]]
    sha256 = "ae3d7a7c05d6ac31ddef83139a9a25bd6c63365f62f1e6db79bb434acbef0869"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.i686-w64-mingw32.tar.gz"
[[ZstdSeekable]]
arch = "powerpc64le"
git-tree-sha1 = "8b33700d154806f59f2a7b5bf18fa7fb641c5582"
libc = "glibc"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "58a1cd620b11bfa930bd17c5b2adada27b8f6631aa37906d7b37475e06f952b6"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.powerpc64le-linux-gnu.tar.gz"
[[ZstdSeekable]]
arch = "riscv64"
git-tree-sha1 = "00466958bc56ec0775719fde5e9814015608e34e"
libc = "glibc"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "67bdfec1dd4b22e52aa3ed1318b33c2793318e5d6797a41f1af0e060c6831436"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.riscv64-linux-gnu.tar.gz"
[[ZstdSeekable]]
arch = "x86_64"
git-tree-sha1 = "e771c737525c72d58a10eb253eb45243378e4750"
os = "macos"

    [[ZstdSeekable.download]]
    sha256 = "b4bec07176a3e651a9bb0caa6f9154e5ef2c4c42521d7358f44a28401941bf26"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.x86_64-apple-darwin.tar.gz"
[[ZstdSeekable]]
arch = "x86_64"
git-tree-sha1 = "a37fd1b6b747e4f3a5ea4b2373d258448d5d9a04"
libc = "glibc"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "7bb388a63ad1b85894da9ed9a94d7493ddb9cb4c7dee3fa5f00145351ecac8ad"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.x86_64-linux-gnu.tar.gz"
[[ZstdSeekable]]
arch = "x86_64"
git-tree-sha1 = "209fa27bb6cf3d1fde759219e238e03efed96b88"
libc = "musl"
os = "linux"

    [[ZstdSeekable.download]]
    sha256 = "c47374b0d0c0fb9fd3d9c2cada2b9be2ec86e7d14e218bcf9172d63253c9816a"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.x86_64-linux-musl.tar.gz"
[[ZstdSeekable]]
arch = "x86_64"
git-tree-sha1 = "ca14ca54da6b1643a553c65025e45593ae4981d4"
os = "freebsd"

    [[ZstdSeekable.download]]
    sha256 = "7d853cb6cc6b30da30e4d5f110c886bdd08326a2bf677e7d60edfa8d5221dd1e"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.x86_64-unknown-freebsd.tar.gz"
[[ZstdSeekable]]
arch = "x86_64"
git-tree-sha1 = "585241af53c4a08ef316ebafad87533ae155ae8a"
os = "windows"

    [[ZstdSeekable.download]]
    sha256 = "92181608993120deb9f9f0cb7b5959655648b5644a9ae88aa18189e7c1b8286b"
    url = "https://github.com/JuliaBinaryWrappers/ZstdSeekable_jll.jl/releases/download/ZstdSeekable-v1.5.7+0/ZstdSeekable.v1.5.7.x86_64-w64-mingw32.tar.gz"
